# post_processing.py
#
# Processes CSV files generated by data_collection.py (or similar format).
# It assumes you have a directory (default: 'runs/') containing CSVs where:
#   - Each CSV's filename starts with a class prefix (e.g., 'circle_data.csv', 'square_data_01.csv').
#   - Each ROW inside the CSV represents a single recorded run/gesture.
#   - Columns are flattened sensor readings (e.g., Sample1_Accel_X, Sample1_Accel_Y, ...).
#
# The script performs the following steps for each class:
# 1. Combines all CSVs belonging to that class.
# 2. Normalizes the length of each run to a fixed number of samples (SAMPLE_NORM).
# 3. Splits the data into training and testing sets based on SPLIT_RATIO.
# 4. Saves the processed sets into 'dataset_train/' and 'dataset_test/' directories.
# 5. Reports the number of runs found for each class.

import os
import glob
import pandas as pd
import numpy as np

# ========================= CONFIGURATION =========================
# 1. Prefixes for your data classes.
#    The script will search for any CSV file starting with these strings.
#    e.g., 'circle' will match 'circle.csv', 'circle_01.csv', etc.
FILENAME_PREFIXES = [
    "circle",
    "square",
    "left-swipe",
]

# 2. The fixed number of samples each run should be normalized to.
#    If a run is longer, it will be downsampled. If shorter, it will be interpolated.
SAMPLE_NORM = 100

# 3. The ratio for splitting data into training and testing sets.
#    0.8 means 80% for training, 20% for testing.
SPLIT_RATIO = 0.8

# 4. Source and destination directories
SOURCE_DIR = "runs"
TRAIN_DIR = "dataset_train"
TEST_DIR = "dataset_test"

# 5. The number of axes/features per sample (e.g., AccelX,Y,Z, GyroX,Y,Z = 6)
FEATURES_PER_SAMPLE = 6
# =================================================================

def resample_run(run_data, target_len, num_features):
    """
    Resamples a single run (a 1D numpy array) to a new length.
    """
    # Drop any NaN padding and find the actual length
    run_data = run_data[~np.isnan(run_data)]
    actual_num_samples = len(run_data) // num_features
    
    if actual_num_samples == 0:
        return np.array([])

    # Reshape from 1D array to 2D array (samples, features)
    reshaped_data = run_data.reshape(actual_num_samples, num_features)
    
    # Create the original and target sample indices for interpolation
    original_indices = np.linspace(0, 1, actual_num_samples)
    target_indices = np.linspace(0, 1, target_len)
    
    # Initialize the resampled data array
    resampled_data = np.zeros((target_len, num_features))
    
    # Interpolate each feature column independently
    for i in range(num_features):
        resampled_data[:, i] = np.interp(target_indices, original_indices, reshaped_data[:, i]).astype(int)
        
    # Flatten back to a 1D array for storage in the final DataFrame
    return resampled_data.flatten()

def process_class(prefix, sample_norm, num_features, split_ratio):
    """
    Finds, loads, normalizes, and splits data for a given class prefix.
    """
    print(f"--- Processing class: '{prefix}' ---")
    
    # Find all CSV files for the current prefix
    search_path = os.path.join(SOURCE_DIR, f"{prefix}*.csv")
    csv_files = glob.glob(search_path)
    
    if not csv_files:
        print(f"No CSV files found for prefix '{prefix}' in '{SOURCE_DIR}'. Skipping.\n")
        return

    # Load and concatenate all found CSVs into a single DataFrame
    df_list = [pd.read_csv(file) for file in csv_files]
    combined_df = pd.concat(df_list, ignore_index=True)
    
    num_runs = len(combined_df)
    if num_runs == 0:
        print(f"Files found for '{prefix}', but they contain no data. Skipping.\n")
        return
        
    print(f"Found {len(csv_files)} file(s) with a total of {num_runs} runs.")

    # Apply resampling to each row (run)
    resampled_runs = combined_df.apply(
        lambda row: resample_run(row.to_numpy(dtype=float), sample_norm, num_features),
        axis=1
    )

    # Convert the list of resampled runs back into a DataFrame
    processed_df = pd.DataFrame(resampled_runs.tolist())

    # Generate new column headers
    headers = []
    labels = ["Accel_X", "Accel_Y", "Accel_Z", "Gyro_X", "Gyro_Y", "Gyro_Z"]
    for i in range(sample_norm):
        headers.extend([f"Sample{i+1}_{label}" for label in labels])
    processed_df.columns = headers[:processed_df.shape[1]]

    # Split the data into training and testing sets
    if num_runs < 2:
        print("Not enough data to split into training and testing sets. Skipping split.")
        train_df, test_df = processed_df, pd.DataFrame()
    else:
        # Shuffle the DataFrame for random splitting
        shuffled_df = processed_df.sample(frac=1, random_state=42).reset_index(drop=True)
        
        # Calculate the split index
        split_idx = int(len(shuffled_df) * split_ratio)
        
        # Split the DataFrame
        train_df = shuffled_df.iloc[:split_idx]
        test_df = shuffled_df.iloc[split_idx:]

    # Save the processed files
    train_filename = os.path.join(TRAIN_DIR, f"{prefix}_training.csv")
    test_filename = os.path.join(TEST_DIR, f"{prefix}_test.csv")
    
    train_df.to_csv(train_filename, index=False)
    print(f"Saved {len(train_df)} training runs to '{train_filename}'")

    if not test_df.empty:
        test_df.to_csv(test_filename, index=False)
        print(f"Saved {len(test_df)} testing runs to '{test_filename}'")
        
    print(f"Total runs processed for '{prefix}': {num_runs}\n")


if __name__ == "__main__":
    # Ensure output directories exist
    os.makedirs(TRAIN_DIR, exist_ok=True)
    os.makedirs(TEST_DIR, exist_ok=True)
    
    print("Starting data post-processing...\n")
    
    for prefix in FILENAME_PREFIXES:
        process_class(prefix, SAMPLE_NORM, FEATURES_PER_SAMPLE, SPLIT_RATIO)
        
    print("All classes processed.")
